/**
 * Sample MBE-style MCQs for seeding (source: practice).
 * topicSlug = topics.slug; subtopicSlug = subtopics.slug
 */
export type MbeSeedProblem = {
  topicSlug: string;
  subtopicSlug: string;
  questionText: string;
  options: [string, string, string, string];
  correctOption: number;
  explanation: string;
  hint: string;
  difficulty: "easy" | "medium" | "hard";
  category?: string;
};

export const MBE_SEED_PROBLEMS: MbeSeedProblem[] = [
  {
    topicSlug: "civil-procedure-jurisdiction-&-venue",
    subtopicSlug: "diversity-jurisdiction",
    questionText:
      "A citizen of State A sues a citizen of State B in federal court for $95,000. Which analysis is correct?",
    options: [
      "Federal diversity jurisdiction exists because complete diversity and amount exceed $75,000.",
      "Federal jurisdiction requires a federal question.",
      "The amount must exceed $100,000.",
      "The defendant must consent to federal jurisdiction.",
    ],
    correctOption: 0,
    explanation:
      "28 U.S.C. § 1332 requires complete diversity and an amount in controversy exceeding $75,000, exclusive of interest and costs.",
    hint: "Diversity threshold is $75,000.",
    difficulty: "easy",
    category: "Civil Procedure",
  },
  {
    topicSlug: "civil-procedure-jurisdiction-&-venue",
    subtopicSlug: "personal-jurisdiction",
    questionText:
      "A nonresident sells via a website accessible in the forum but has no offices there. The key due process inquiry is:",
    options: [
      "Whether the defendant purposely availed itself of the forum",
      "Whether the forum has a long-arm statute",
      "Whether venue is proper under § 1391",
      "Whether the plaintiff is a forum resident",
    ],
    correctOption: 0,
    explanation:
      "Specific jurisdiction requires minimum contacts and purposeful availment related to the suit.",
    hint: "International Shoe — minimum contacts.",
    difficulty: "medium",
    category: "Civil Procedure",
  },
  {
    topicSlug: "civil-procedure-adjudication-&-appeal",
    subtopicSlug: "summary-judgment",
    questionText: "The standard for summary judgment under Rule 56 is:",
    options: [
      "No genuine dispute of material fact and movant entitled to judgment as a matter of law",
      "Evidence viewed in the light most favorable to the movant",
      "The court weighs credibility",
      "Available only after all discovery closes on every claim in the case",
    ],
    correctOption: 0,
    explanation: "Rule 56(a) — no genuine dispute of material fact.",
    hint: "Rule 56 material facts standard.",
    difficulty: "easy",
    category: "Civil Procedure",
  },
  {
    topicSlug: "civil-procedure-adjudication-&-appeal",
    subtopicSlug: "claim-preclusion-res-judicata",
    questionText:
      "A prior jury found Driver negligent but awarded zero damages. May a different passenger relitigate negligence?",
    options: [
      "No — claim preclusion bars relitigation of negligence",
      "Yes — zero damages means no claim",
      "Yes — different plaintiff",
      "No — only if same court",
    ],
    correctOption: 0,
    explanation: "Claim preclusion bars relitigation of claims actually decided or that could have been raised.",
    hint: "Res judicata / claim preclusion.",
    difficulty: "hard",
    category: "Civil Procedure",
  },
  {
    topicSlug: "constitutional-law-judicial-power-&-federalism",
    subtopicSlug: "standing-ripeness-&-mootness",
    questionText:
      "Congress grants all taxpayers standing to sue whenever they object to any federal expenditure. The statute is:",
    options: [
      "Invalid — Article III limits generalized taxpayer grievances",
      "Valid — Congress defines all standing",
      "Valid only for Establishment Clause challenges to specific expenditures",
      "Valid only for state taxpayers in federal court",
    ],
    correctOption: 0,
    explanation: "Congress cannot create Article III standing for generalized grievances; Flast is narrow.",
    hint: "Article III limits on standing.",
    difficulty: "medium",
    category: "Constitutional Law",
  },
  {
    topicSlug: "constitutional-law-individual-rights-—-due-process",
    subtopicSlug: "substantive-due-process",
    questionText: "A state bans abortions after six weeks. Likely standard of review:",
    options: ["Strict scrutiny", "Rational basis", "Intermediate scrutiny", "Political question"],
    correctOption: 0,
    explanation: "Fundamental liberty interests trigger strict scrutiny.",
    hint: "Fundamental rights → strict scrutiny.",
    difficulty: "medium",
    category: "Constitutional Law",
  },
  {
    topicSlug: "constitutional-law-equal-protection-&-first-amendment",
    subtopicSlug: "equal-protection-—-rational-basis",
    questionText: "A city requires municipal employees to live in the city. Standard of review:",
    options: ["Rational basis", "Strict scrutiny", "Intermediate scrutiny", "No review"],
    correctOption: 0,
    explanation: "Residency rules for public employment typically get rational basis review.",
    hint: "No suspect class → rational basis.",
    difficulty: "easy",
    category: "Constitutional Law",
  },
  {
    topicSlug: "constitutional-law-equal-protection-&-first-amendment",
    subtopicSlug: "freedom-of-religion-—-establishment-clause",
    questionText:
      "A public university denies funding to groups requiring a theistic belief. Best analysis:",
    options: [
      "Likely unconstitutional viewpoint/belief discrimination in funding",
      "Valid because religion is involved",
      "Rational basis only",
      "Universities may discriminate among all viewpoints",
    ],
    correctOption: 0,
    explanation: "Viewpoint discrimination in access to funding forums violates the First Amendment.",
    hint: "Viewpoint neutrality in public funding.",
    difficulty: "hard",
    category: "Constitutional Law",
  },
  {
    topicSlug: "contracts",
    subtopicSlug: "formation-offer-acceptance-consideration",
    questionText:
      "Buyer accepts on June 1 delivery; Seller offered May 15. Under UCC Article 2:",
    options: [
      "Contract forms unless delivery date materially alters the offer",
      "No contract — counteroffer",
      "Fax cannot accept goods contracts",
      "Contract only with confirming PO",
    ],
    correctOption: 0,
    explanation: "UCC § 2-207 battle of the forms.",
    hint: "UCC 2-207 material alteration.",
    difficulty: "medium",
    category: "Contracts",
  },
  {
    topicSlug: "contracts",
    subtopicSlug: "defenses-to-formation",
    questionText: "Party signs while severely intoxicated and unable to understand the transaction:",
    options: [
      "Voidable for lack of capacity",
      "Void for illegality",
      "Statute of frauds bars enforcement",
      "No defense for intoxication",
    ],
    correctOption: 0,
    explanation: "Intoxication can void a contract when understanding was lacking and the other party knew or should have known.",
    hint: "Capacity → voidable.",
    difficulty: "easy",
    category: "Contracts",
  },
  {
    topicSlug: "contracts",
    subtopicSlug: "breach-&-anticipatory-repudiation",
    questionText: "Seller repudiates before delivery date. Buyer may:",
    options: [
      "Treat as immediate breach and sue",
      "Wait only until delivery date",
      "Sue only if Seller retracts",
      "Recover restitution only",
    ],
    correctOption: 0,
    explanation: "Anticipatory repudiation permits immediate breach treatment.",
    hint: "UCC 2-610 / Restatement § 253.",
    difficulty: "medium",
    category: "Contracts",
  },
  {
    topicSlug: "contracts",
    subtopicSlug: "remedies-expectation-reliance-restitution",
    questionText:
      "Owner cancels $20,000 renovation after Builder spent $4,000 and would have earned $5,000 profit. Expectation measure ≈",
    options: [
      "$5,000 lost profit plus recoverable costs minus avoided costs",
      "$20,000 automatically",
      "$4,000 only",
      "$0",
    ],
    correctOption: 0,
    explanation: "Expectation damages put the party in the position of full performance.",
    hint: "Lost profit + costs − savings.",
    difficulty: "hard",
    category: "Contracts",
  },
  {
    topicSlug: "criminal-law-substantive-criminal-law",
    subtopicSlug: "homicide",
    questionText: "Defendant shoots intending only a wound; Victim dies. Most likely:",
    options: [
      "Murder — malice may be inferred",
      "Battery only",
      "Manslaughter only",
      "No homicide without premeditation",
    ],
    correctOption: 0,
    explanation: "Intent to cause serious bodily harm can satisfy malice.",
    hint: "Malice without intent to kill.",
    difficulty: "medium",
    category: "Criminal Law",
  },
  {
    topicSlug: "criminal-law-criminal-procedure",
    subtopicSlug: "fourth-amendment-—-search-&-seizure",
    questionText: "Traffic stop; police search trunk from marijuana odor without warrant:",
    options: [
      "Automobile exception requires PC and proper scope",
      "Plain view always allows trunk search",
      "Inventory search rule applies",
      "Stop invalid so search is fine",
    ],
    correctOption: 0,
    explanation: "Automobile exception needs probable cause and scope limited to where evidence may be found.",
    hint: "PC + scope under automobile exception.",
    difficulty: "hard",
    category: "Criminal Procedure",
  },
  {
    topicSlug: "criminal-law-substantive-criminal-law",
    subtopicSlug: "defenses-—-justification",
    questionText: "Defendant reasonably but mistakenly believed force was necessary. Self-defense:",
    options: [
      "Available if belief was reasonable",
      "Only if belief was correct",
      "Never for mistakes",
      "Requires retreat always",
    ],
    correctOption: 0,
    explanation: "Reasonable mistake as to necessity can support self-defense in modern codes.",
    hint: "Reasonable mistake of fact.",
    difficulty: "easy",
    category: "Criminal Law",
  },
  {
    topicSlug: "criminal-law-criminal-procedure",
    subtopicSlug: "sixth-amendment-—-right-to-counsel",
    questionText: "Suspect invokes counsel; police question on another crime without counsel:",
    options: [
      "Inadmissible — Edwards rule",
      "Admissible — different offense",
      "Admissible if Miranda re-read",
      "Admissible with written waiver only",
    ],
    correctOption: 0,
    explanation: "Edwards v. Arizona bars police-initiated interrogation after counsel is invoked.",
    hint: "Edwards after counsel invocation.",
    difficulty: "medium",
    category: "Criminal Procedure",
  },
  {
    topicSlug: "evidence-hearsay-&-impeachment",
    subtopicSlug: "hearsay-definition-&-non-hearsay-uses",
    questionText:
      "Witness: 'The paramedic said the driver ran the red light,' offered for truth. This is:",
    options: [
      "Hearsay — each layer needs an exception",
      "Non-hearsay automatically",
      "Excited utterance",
      "Admissible — paramedic unavailable",
    ],
    correctOption: 0,
    explanation: "Out-of-court statements offered for truth are hearsay; nested hearsay needs two bases.",
    hint: "Identify each layer offered for truth.",
    difficulty: "medium",
    category: "Evidence",
  },
  {
    topicSlug: "evidence-relevance-&-character",
    subtopicSlug: "relevance-&-probative-value",
    questionText: "Court excludes prior bankruptcies in a contract case. Likely:",
    options: [
      "Rule 403 — unfair prejudice outweighs probative value",
      "Rule 404(b) character",
      "Hearsay",
      "Best evidence rule",
    ],
    correctOption: 0,
    explanation: "FRE 403 balancing.",
    hint: "Relevant but excluded for prejudice.",
    difficulty: "easy",
    category: "Evidence",
  },
  {
    topicSlug: "evidence-hearsay-&-impeachment",
    subtopicSlug: "impeachment-—-prior-inconsistent-statement",
    questionText: "May counsel impeach with a prior tax fraud conviction?",
    options: [
      "Yes — subject to FRE 609 limits",
      "Never",
      "Only if witness opens door on direct",
      "Only prosecutor may impeach",
    ],
    correctOption: 0,
    explanation: "FRE 609 governs impeachment by conviction.",
    hint: "Rule 609.",
    difficulty: "easy",
    category: "Evidence",
  },
  {
    topicSlug: "evidence-privileges-&-authentication",
    subtopicSlug: "attorney-client-privilege",
    questionText: "Client consults lawyer; spouse seeks testimony about the consultation:",
    options: [
      "Privilege belongs to client and protects confidential legal advice",
      "Belongs to attorney only",
      "No privilege in civil cases",
      "Waived by marriage",
    ],
    correctOption: 0,
    explanation: "Attorney-client privilege protects confidential communications for legal advice.",
    hint: "Client holds the privilege.",
    difficulty: "easy",
    category: "Evidence",
  },
  {
    topicSlug: "real-property-estates-&-concurrent-ownership",
    subtopicSlug: "landlord-tenant-—-duties-&-remedies",
    questionText: "Tenant breaks lease early; landlord re-rents at same rent. Tenant owes:",
    options: [
      "Mitigated — no rent if landlord successfully re-rented",
      "Full term rent regardless",
      "One month only",
      "Nothing if habitability issue unpled",
    ],
    correctOption: 0,
    explanation: "Landlord must mitigate by reasonable re-rental efforts.",
    hint: "Mitigation of damages.",
    difficulty: "medium",
    category: "Real Property",
  },
  {
    topicSlug: "real-property-recording-&-adverse-possession",
    subtopicSlug: "recording-acts-—-race-notice-race-notice",
    questionText: "A sells to B (unrecorded), then to BFP C who records. Race-notice statute:",
    options: [
      "C wins if no notice and recorded first",
      "A wins — first buyer",
      "Grantor keeps title",
      "Recorder decides",
    ],
    correctOption: 0,
    explanation: "Race-notice: subsequent BFP without notice who wins recording race prevails.",
    hint: "Notice + recording race.",
    difficulty: "medium",
    category: "Real Property",
  },
  {
    topicSlug: "real-property-estates-&-concurrent-ownership",
    subtopicSlug: "future-interests-reversions-remainders-executory-interests",
    questionText: "O to A for life, then to B and her heirs. B has:",
    options: [
      "Vested remainder",
      "Contingent remainder",
      "Life estate pur autre vie",
      "Executory interest",
    ],
    correctOption: 0,
    explanation: "Ascertained remainderman, no condition precedent → vested remainder.",
    hint: "Life estate + remainder.",
    difficulty: "hard",
    category: "Real Property",
  },
  {
    topicSlug: "real-property-land-transactions-&-nonpossessory-interests",
    subtopicSlug: "foreclosure-&-redemption",
    questionText: "Foreclosure sale yields less than debt. In recourse jurisdiction:",
    options: [
      "Deficiency judgment may be available",
      "No further recovery",
      "Automatic seizure of all assets",
      "Only if fraud",
    ],
    correctOption: 0,
    explanation: "Recourse mortgages may yield deficiency judgments after foreclosure.",
    hint: "Shortfall after foreclosure sale.",
    difficulty: "easy",
    category: "Real Property",
  },
  {
    topicSlug: "torts-negligence",
    subtopicSlug: "duty-—-general-&-special-relationships",
    questionText: "Driver runs stop sign; hits lawful pedestrian. Best theory:",
    options: [
      "Negligence",
      "Strict products liability",
      "IIED only",
      "Assumption of risk",
    ],
    correctOption: 0,
    explanation: "Classic negligence — duty, breach, causation, damages.",
    hint: "Traffic violation + injury.",
    difficulty: "easy",
    category: "Torts",
  },
  {
    topicSlug: "torts-intentional-torts",
    subtopicSlug: "battery-&-assault",
    questionText: "Intentional harmful contact without consent:",
    options: ["Battery", "Assault only", "False imprisonment", "Trespass to land"],
    correctOption: 0,
    explanation: "Battery = intentional harmful or offensive contact.",
    hint: "Contact + intent.",
    difficulty: "easy",
    category: "Torts",
  },
  {
    topicSlug: "torts-strict-liability-&-defamation",
    subtopicSlug: "defamation-—-libel-&-slander",
    questionText: "False crime accusation published to third parties; private plaintiff:",
    options: [
      "Must prove at least negligence and damages (or per se)",
      "Strict liability always",
      "Actual malice always",
      "Only dislike required",
    ],
    correctOption: 0,
    explanation: "Private figures generally need negligence; public figures need actual malice.",
    hint: "Gertz / NY Times standards.",
    difficulty: "medium",
    category: "Torts",
  },
  {
    topicSlug: "torts-strict-liability-&-defamation",
    subtopicSlug: "products-liability-—-manufacturing-defect",
    questionText: "Tool explodes due to manufacturing defect. Strict liability requires:",
    options: [
      "Defect when product left control and injury from foreseeable use",
      "Manufacturer negligence",
      "Manufacturer knew of defect",
      "Consumer assumed risk by buying tools",
    ],
    correctOption: 0,
    explanation: "Strict products liability — defect, causation, foreseeable use.",
    hint: "Defect + causation, not fault.",
    difficulty: "medium",
    category: "Torts",
  },
];
